/* Html5Oyunlar 2016 */
Html5Oyunlar(["SWP","DOMSelect","SWPUtils","DOMEvent"],function(f,e,b,d){f.init("game_side_panel");var g=window,r=g.document,v=f.getProperty("app_id"),h=f.getProperty("menu_behaviour"),c=r.getElementById("wdg_game_side_panel"),k=e.getAll("touch"===h?".tab":".game-tab",c),m=!1,l,n,w=g.getComputedStyle?parseFloat(g.getComputedStyle(c).fontSize):16,t=function(a){switch(h){case "touch":b.removeClass(e.get('[data-tab="'+a+'"] .notification',c),"is-hidden");break;case "hover":b.addClass(e.get(".game-tab--"+
a),"is-active")}},x=function(a){a=a||window.event;a=(a.target||a.srcElement).getAttribute("data-child");var c=e.get(".coach-last-played");c&&b.addClass(c,"is-hidden");a&&f.System.emit("game.sidepanel.open",{item:a})},u=function(a){var c=e.get(".game-tab--"+a);c&&(b.addClass(c,"is-extended"),f.System.emit("game.sidepanel.open",{item:a}))},p=function(){b.each(k,function(a){b.removeClass(a,"is-extended")})},q=function(){m&&(m=!1,b.removeClass(l,"is-open"),b.removeClass(n,"is-open"),n=l=void 0)},y=function(a){return"show"+
a.replace(/(?:^|_)([a-z])/g,function(a,b){return b.toUpperCase()})};(function(){d.add(c,"click",function(a){a=a||g.event;a=a.target||a.srcElement;b.hasClass(a,"login-trigger")&&f.System.emit("popup.login.open");b.hasClass(a,"register-trigger")&&f.System.emit("popup.register.open")});switch(h){case "touch":d.add(r,"click",function(a){if(m){a=a||g.event;for(a=a.target||a.srcElement;a;){if(c===a)return;a=a.parentNode}q()}});b.each(k,function(a){d.add(a,"click",function(){var d=a.getAttribute("data-tab");
if(l!==a){f.System.emit("game.sidepanel.open",{item:d});Html5Oyunlar("tracker.event.express",{data:{eventCategory:"page",eventAction:"gamePageFeature",eventLabel:y(d),properties:{applicationId:v}}});var g=e.get('[data-tab="'+d+'"]',c),d=e.get('[data-panel="'+d+'"]',c),h=e.get(".notification, .notification--count",g),k=c.getBoundingClientRect().left/w;q();21>k?b.addClass(c,"open-inside"):b.removeClass(c,"open-inside");m=!0;l=g;n=d;b.addClass(l,"is-open");b.addClass(n,"is-open");h&&b.addClass(h,"is-hidden")}else q()})});
break;case "hover":d.add(c,"mouseover",x),d.add(".game-tabs","mouseover",p),b.each(k,function(a){d.add(a,"mouseover",function(){b.removeClass(a,"is-active")})})}})();f.System.init(function(a){switch(a.name){case "game.update.achievement":case "game.update.achievement.failed":p();t("awards");u("awards");break;case "game.update.highscore":case "game.update.highscore.failed":p();t("highscores");u("highscores");break;case "walkthrough.available":(a=e.get(".game-tab--walkthrough",c)||e.get('[data-tab="walkthrough"]',
c))&&b.removeClass(a,"is-hidden")}})});
/* Html5Oyunlar 2016 */
Html5Oyunlar(["SWP","DOMEvent"],function(f,h){var m,r;function t(){return b||d.getElementById("flashgame")||d.getElementById("iframegame")}function v(a){b=t();var c=k.innerHeight||d.documentElement.clientHeight,e=p?p.clientWidth:g,f=100/(c/b.clientHeight),h=100/(e/b.clientWidth),m=h>f?e/g*100-50:c/l*100-50,c=h>f?e/g*100:c/l*100,n;"in"===a?q=n=Math.min(q+10,c):"out"===a&&(q=n=Math.max(q-10,m));a=Math.floor(g*n/100);n=Math.floor(l*n/100);b.style.width=a+"px";b.style.height=n+"px"}f.init("zoom_bar");var k=
window,d=k.document,y=d.getElementById("wdg_zoom_bar"),z=d.getElementById("zoom-in"),A=d.getElementById("zoom-out"),B=d.getElementById("zoom-fullscreen"),g=f.getProperty("game_width"),l=f.getProperty("game_height"),u,b,w,x,p=d.getElementById("theGame"),q=100;w=function(){b=t();b.style.width=u+"px";b.style.height=originalGameHeight+"px";f.Utils.removeClass(d.body,"fullscreen");var a=d.querySelector(".icon--close");a.parentNode.removeChild(a)};x=function(){var a=l,c=g,a=parseInt(a,10),c=parseInt(c,
10),e=k.innerHeight||d.documentElement.clientHeight,f=(p?p.clientWidth:c)/c,e=a*f>e?e/a:f;m=a*e;r=c*e;b.style.width=r+"px";b.style.height=m+"px";g=b.clientWidth;l=b.clientHeight;q=100};h.add(B,"click",function(){b=t();u=b.clientWidth;var a=originalGameHeight=b.clientHeight,c=u,a=parseInt(a,10),c=parseInt(c,10),e=k.innerHeight||d.documentElement.clientHeight,g=k.innerWidth||d.documentElement.clientWidth,e=Math.max(Math.min((g-120)/c,e/a),Math.min(g/c,(e-120)/a));m=a*e;r=c*e;b.style.width=r+"px";b.style.height=
m+"px";f.Utils.addClass(d.body,"fullscreen");a=d.createElement("span");a.className="icon--close";p.appendChild(a);h.add(a,"click",w)});h.add(A,"click",function(){v("out")});h.add(z,"click",function(){v("in")});document.querySelector("html.ie8")||h.add(k,"resize",function(){var a;return function(){k.clearTimeout(a);a=k.setTimeout(x,250)}}());f.System.init(function(a){switch(a.name){case "game.display":f.Utils.removeClass(y,"is-hidden");l=(b=t())?b.clientHeight:l;g=b?b.clientWidth:g;break;case "popup.header.open":f.Utils.removeClass(d.body,
"fullscreen")}})});

